### ISSUE TITLE
usb stick not bootable?

### ISSUE THREAD

**Issue by zmike** [eballetbo/chromebooks#43]
I've tried following the howto here: https://blog.dowhile0.org/2022/11/04/how-to-install-fedora-on-an-hp-x2-chromebook/

The size of the boot partition appears to be too small; the kernel.vboot file is greater than the 64mb allotted. I increased this to 128mb, and the script finishes without issues. When I then try to boot the USB stick, I get a black screen and nothing loads.

Is this a known issue?

**Comment by eballetbo** [comment]
Can you paste the output of the script. I just generated a new one and kernel.vboot file is lower than 64mb.

```
 Deploy vboot image on the boot partition...
 13+1 records in
 13+1 records out
 55619584 bytes (56 MB, 53 MiB) copied, 35.5075 s, 1.6 MB/s
 Done.
```

**Comment by zmike** [comment]
Using `tools/image-installer/fedora-workstation-38-aarch64` I get

```
Deploy vboot image on the boot partition...
17+1 records in
17+1 records out
74113024 bytes (74 MB, 71 MiB) copied, 0.974381 s, 76.1 MB/s
Done.
```

**Comment by eballetbo** [comment]
Hi zmike,

Sorry for the taking too long to be back, I was on vacation. Any news on that? Actually I'm still unable to reproduce this, so I'd like to understand better your setup if possible to see if there is something that makes any difference.

**Comment by zmike** [comment]
I think Javier can probably fill you in since we worked on it for a few days, but it seems like some quirk with the exact revision of my hardware

**Comment by eballetbo** [comment]
@zmike I think the problem has been solved? Can I close this issue?

**Comment by zmike** [comment]
It wasn't solved, but I'm also not actively trying to resolve it.
